### ISSUE TITLE
Is self-hosting dead?

### ISSUE THREAD

**Issue by teaminverso** [CapSoftware/Cap#1314]
I've tried deploying using my own docker and railway. Both exhibit the same behavior. I cannot sign up and clicking on the Google and SSO links do nothing.

**Comment by andrew-x** [comment]
I don't think Google and SSO works for self hosting

But make sure you setup your email provider with Resend, the normal email login works for me

**Comment by teaminverso1** [comment]
> I don't think Google and SSO works for self hosting
> 
> But make sure you setup your email provider with Resend, the normal email login works for me

Thanks for the quick reply - I don't want to use Google or SSO. I've already added RESEND_API_KEY and RESEND_FROM_DOMAIN but I still get redirect back to /login when I click the /signup link.

**Comment by teaminverso1** [comment]
Sooooooo.... you don't click on "Sign up here" from the login page if you don't have an account. You type in your email and you get a verification code sent. 

Is this the expected behavior? I would think the messaging should be worded better, if so.

**Comment by Brendonovich** [comment]
`/signup` not working was a bug that's fixed in the latest release, fwiw both routes do the same thing

**Comment by teaminverso1** [comment]
> `/signup` not working was a bug that's fixed in the latest release, fwiw both routes do the same thing

I'm running the latest release and /signup is not working for me.

**Comment by Brendonovich** [comment]
Are you using image `4bc3e41492d9716bf42ff8be1ced004179bceea8d4a28413aea942f50b778c35`? I'm using that + the following envs and was able to make a new account with `/signup`

<img width="642" height="448" alt="Image" src="https://github.com/user-attachments/assets/a5650028-ed44-49e2-b664-80482e999a0a" />

**Comment by nkhi** [comment]
Hi @richiemcilroy - this issue is still lingering. Attempting to spin up a new railway deployment using the instructions at https://cap.so/docs/self-hosting is broken. No magic links for new user signups are printed to Railway logs, effectively blocking any self-hosted usage. Was wondering how we could get this prioritized :)

**Comment by richiemcilroy** [comment]
Fix for this is coming soon - I believe fresh deployments right now are blocked because of the new MinIO deployment issues. Will fix this as soon as 0.4.0 is released next week.

**Comment by nkhi** [comment]
Hey @richiemcilroy - Thanks for the reply. I continued debugging and identified a timing issue in the initial migration that runs when you set up the railway template. I've included a Loom below for context. Hope this helps. Happy holidays!

ps - I also went back and deployed a new template and refreshed the DB table page before redeploying the server, and I'm positive that the database is just not being initialized.

<details><summary>Details</summary>
<p>

## Overview

A timing issue occurs during the deployment of a new instance on Railway, where the database migrations do not complete before the server attempts to access the database. This results in a database with no tables, blocking the user from starting a new instance until the deployment is re-triggered.

## Steps to Reproduce

1. Spin up a new container on Railway.
2. Observe the database, which initially shows no tables.
3. Attempt to access the application, noting the UI toast error indicating the server process is failing.
4. Re-deploy the application to force the migrations to run again.
5. After re-deployment, check the database for tables and attempt to sign up.

## Acceptance Criteria

- The application should successfully connect to the MySQL database without requiring a re-deployment.
- Database migrations should complete before the server attempts to access the database.
- Users should be able to see the database tables immediately after deployment without errors.

</p>
</details>

**Comment by richiemcilroy** [comment]
Forbidden URL sorry 🙈

**Comment by richiemcilroy** [comment]
Self-hosting is actively maintained, and the issues raised around this time have since been fixed. Please open a fresh issue if you hit something specific on the latest release.
